### PR TITLE
Get the core functional again

### PR DESCRIPTION
**Pull request by ghost**
A user reached out to me on to fix this as mame2000 libretro is broke pending pull requests being fixed.

### CODE REVIEW

**Comment by cmitu** [comment]
I can confirm this fixes the emulator, before the the patch the few tests I've run didn't even get the game started (tried with `robby` and `willow`). I'll need to test the input handling, didn't work outright, but I'll get a keyboard to set it up.

Thanks for the patch.

**Comment by ghost** [comment]
if there is issues let me know ill take a look should be too hard to fix if somethings amiss

**Comment by cmitu** [comment]
I tested the input part and it's no problem. 
I don't think hotplugging is supported by this Mame version, that's why I had an issue initially.

**Comment by ghost** [comment]
Well that's some good news for users with less powerful pis.

**Comment by joolswills** [comment]
Are you able to give any more information on the changes ? Both changes are needed to fix loading ? or one is a compilation / warning fix ? Just wondering - both look fine apart from the return indentation which I can change (although the file itself has plenty of existing indentation issues), but I was hoping to make the commit messages a little more verbose

**Comment by ghost** [comment]
the memory fixes are so pi3 will compile and handle addressing properly you can leave that out if you want but newer compilers wont compile it at all and youll could have memory addressing issues. 

https://github.com/RetroPie/mame4all-pi/blob/665c310cb91fbebdd8839d15f3166cf25814ed49/src/osdepend.h#L13-L17

The code here sets this from gcc flags its not user defined. 

The return should fix it in itself as is if your choose not to add it should still work that is the real issue stopping it. It wont compile with raspberry pi3 flags either unless you update the cyclone code youll see the error if you try.

**Comment by joolswills** [comment]
Thanks. Sorry for the delay.

I will look into compiling on rpi3. 

I have changed the indent of the return and added some more information to the cast change commit. Appreciate the additional detail.

**Comment by joolswills** [comment]
Binaries have been rebuilt.

**Pull request merged**
